/* Ripple Map v1: the deep-evidence renderers (Could it be luck?, the forecast check, the drawers). Loaded on the first card open so the
   page's initial JS stays inside the 150 KB budget. Pure functions of the payload; no number is typed here. */
(function (global) {
  let P, TIER, esc, fmtDay, fmtDayY, ROOT;
  function init(ctx) { ({ P, TIER, esc, fmtDay, fmtDayY, ROOT } = ctx); global.RMEvidence._ready = true; }
  function luckPanel(e) {
    if (!e.engine || !e.engine.n_date || e.engine.exceed_topic == null) return `<p>${e.fluke ? esc(e.fluke.text) : 'This stop has not been tested against lookalikes yet.'}${e.fluke && e.fluke.f_1_in ? ` Decoy links this strong turn out to be flukes about 1 in ${e.fluke.f_1_in} times.` : ''} The full placebo families (fake dates, other series, random links) arrive with this event's pond payload.</p>`;
    const g = e.engine, fam = [
      { name: `${g.n_date.toLocaleString()} fake dates, same series`, n: g.n_date, hits: g.exceed_date, p: g.p_date },
      { name: `${g.n_topic} other series, same date`, n: g.n_topic, hits: g.exceed_topic, p: g.p_topic },
      { name: `${g.n_link} random links`, n: g.n_link, hits: g.exceed_link, p: g.p_link }];
    const rows = fam.map(f => `<div class="pf"><span>${esc(f.name)}</span><span class="pf-bar" aria-hidden="true"><i style="width:${Math.max(1.5, Math.min(100, f.hits / f.n * 100))}%"></i></span><b class="num">${f.hits} of ${f.n}</b><small>about 1 in ${Math.round(1 / f.p)}</small></div>`).join('');
    let sv = '', tail = '';
    if (e.contrast) {
      const c = e.contrast, v = c.in_time.values_logpts.map(x => Math.abs(x - c.in_time.centre) * 100), real = Math.abs(c.d_logpts - c.in_time.centre) * 100;
      const w = 420, h = 100, bins = 26, mx = Math.max(real * 1.08, Math.max(...v) * 1.1), cnt = new Array(bins).fill(0);
      v.forEach(x => cnt[Math.min(bins - 1, Math.floor(x / mx * bins))]++);
      const top = Math.max(...cnt), bw = (w - 20) / bins;
      sv = `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${c.in_time.n} pseudo-storms at the same date in other years: the size of the Florida-minus-donors gap each produced. The real storm's gap of ${Math.round(real)} points sits beyond every one of them.">`;
      cnt.forEach((n, i) => { const bx = i * bw, bh = n / top * (h - 34); sv += `<rect class="bar ${i * mx / bins >= real ? 'tail' : ''}" x="${bx + 1}" y="${h - 20 - bh}" width="${bw - 2}" height="${bh}" rx="1.5"/>`; });
      const rx = Math.min(w - 20, real / mx * (w - 20));
      sv += `<line class="you" x1="${rx}" x2="${rx}" y1="4" y2="${h - 20}"/><text class="lab strong" x="${rx - 6}" y="12" text-anchor="end">this storm, ${Math.round(real)} pts</text><text class="lab" x="0" y="${h - 5}">${c.in_time.n} pseudo-storms, same dates in other years</text><text class="lab" x="${w - 20}" y="${h - 5}" text-anchor="end">bigger gap →</text></svg>`;
      tail = `<h4>And against the rest of the country</h4>${sv}<p>${c.in_time.n_bigger === 0 ? 'None' : c.in_time.n_bigger} of the ${c.in_time.n} pseudo-storms came close (in-time p ${c.p_time}). Against ${c.n_donors} unaffected regions shuffled into 30 fake Floridas, the real pair ranked first: about <b>1 in ${c.p_space_odds}</b>.</p>`;
    }
    return `<div class="luck"><div class="pfs" role="list" aria-label="Placebo families for the single-event test">${rows}</div><p>The engine's single-event test: T ${g.t_stat.toFixed(2)}${g.bh ? `, corrected over ${g.bh.m} tests` : ''} (q ${g.q_w.toFixed(3)}). A random date on this series looks this strong about <b>1 in ${Math.round(1 / g.p_date)}</b> times.${g.f === 1 ? ' The calibrated fluke rate for this T bin is still warming up (too few decoys), so no fluke odds are quoted here.' : ''}</p>${tail}</div>`;
  }
  /* the third independent check: an ARIMA forecast of each series, per-series effect with its interval */
  function forecastPanel(e) {
    const f = e.forecast; if (!f) return '';
    const lo = Math.min(...f.series.map(s => s.lo_pct), 0) - 3, hi = Math.max(...f.series.map(s => s.hi_pct), 0) + 3, X = v => (v - lo) / (hi - lo) * 100;
    return `<div class="sect" id="forecast"><h3>An independent forecast model${f.state === 'agree' ? ' agrees' : f.state === 'pending' ? ' has not checked yet' : ' disagrees'}</h3><p>${esc(f.text)}</p><div class="fc">${f.series.map(s => `<div class="row"><span>Series ${s.series_id}, ${s.pre_days} days of history, ${s.post_days} days after onset</span><b>${s.effect_pct}% [${s.lo_pct}, ${s.hi_pct}]</b><div class="ci" role="img" aria-label="${s.effect_pct}% against the forecast, 95% interval ${s.lo_pct} to ${s.hi_pct}"><i style="left:${X(s.lo_pct)}%;width:${X(s.hi_pct) - X(s.lo_pct)}%"></i><em style="left:${X(0)}%"></em><b style="left:${X(s.effect_pct)}%"></b></div></div>`).join('')}<small>Zero is the model's own forecast (the thin line). Model ${esc(f.model)}, horizon ${f.horizon_days} days, evaluated ${fmtDayY(f.evaluated_at)}. ${esc(f.calib_text)}</small></div></div>`;
  }
  function drawers(e) {
    if (!e.engine) return `<details class="drawer"><summary>Where the numbers come from</summary><p>This stop is drawn from the story layer's public payload (story ${esc(e.story_id || '')}, version ${P.version}): tier, effect, lag and the placebo odds above. The series chart, the three placebo families, the regional contrast and the ledger sequence numbers arrive with the event's pond payload. Until then the card shows only what has been published.</p><p><a href="${ROOT}how/">How Ripple Map knows</a>.</p></details>`;
    const c = e.contrast, L = e.ledger, led = P.ledger;
    const row = (k, v, h) => `<dt>${k}</dt><dd${h ? ' class="h"' : ''}>${v}</dd>`;
    const g = e.engine;
    return `<details class="drawer"><summary>The single-event test (engine ${esc(g.version)})</summary><dl class="dl">
      ${row('Series', e.node + ' (hop ' + e.hop_id + ')')}${row('Observed onset', fmtDayY(e.onset_observed) + ', lag ' + e.lag_from_event_days + ' d from the event')}${g.rho && typeof g.rho === 'object' && g.rho.shrunk != null ? row('Effect (shrunk)', g.rho.shrunk.toFixed(3) + '× [' + g.rho.lo.toFixed(3) + ', ' + g.rho.hi.toFixed(3) + ']' + (g.rho.raw != null ? '; raw ' + g.rho.raw.toFixed(3) : '')) : row('Effect', e.num || 'not yet published')}
      ${e.chart && e.chart.peak ? row('Peak day', fmtDayY(e.chart.peak.d) + ', ' + Math.round(e.chart.peak.t * 100) + '% of normal') : ''}${g.t_stat != null ? row('T statistic', g.t_stat.toFixed(3)) : ''}${g.n_date ? row('Fake dates', `${g.exceed_date} of ${g.n_date} (p ${g.p_date.toFixed(4)})`) : ''}${g.n_topic ? row('Other series', `${g.exceed_topic ?? '–'} of ${g.n_topic} (p ${g.p_topic})`) : ''}${g.n_link ? row('Random links', `${g.exceed_link ?? '–'} of ${g.n_link} (p ${g.p_link.toFixed(3)})`) : ''}
      ${g.bh ? row('BH (m ' + g.bh.m + ', weight ' + g.bh.weight + ')', 'q ' + g.q_w.toFixed(4)) : row('Corrected q', g.q_w != null ? g.q_w.toFixed(4) : '–')}${g.channels ? row('Channels', g.channels.agree + ' of ' + g.channels.of + (g.channels.names ? ' (' + g.channels.names.join(', ') + ')' : '')) : ''}${row('Fluke-rate bin', `T ${g.f_bin}: reads ${g.f}${g.f === 1 ? ' (warming up: too few decoys in this bin yet)' : ''}`)}${row('Flags / fails', ((g.flags || []).join(', ') || 'none') + ' / ' + ((g.fails || []).join(', ') || 'none'))}
      ${row('Engine tier', TIER[e.engine_tier])}${e.published.ce ? row('Forecast gate', `${e.published.tier} (${e.published.reason || 'agrees'}; mode ${e.published.mode}; state ${e.published.ce.state}${e.published.ce.n_agree != null ? `, ${e.published.ce.n_agree} of ${e.published.ce.n_eligible} series agree` : ''})`) : ''}</dl>${g.f_note ? `<p>${esc(g.f_note)}</p>` : ''}</details>
      ${c ? `<details class="drawer"><summary>The regional contrast (engine 6.2.1)</summary><dl class="dl">
      ${row('Treated regions', c.treated.join(' + ') + ' (Florida)')}${row('Donor regions', c.n_donors)}${row('Window', `${c.window.pre_days} d before, ${c.window.post_days} d after ${fmtDayY(c.window.onset)}`)}
      ${row('Treated change alone', c.treated_only_pct + '%')}${row('Contrast (treated − donors)', c.d_logpts + ' log pts = ' + c.effect_pct + '%')}${row('Centred on in-time median', c.d_centred + ' log pts')}
      ${row('Robust se (1.4826 · MAD)', c.se)}${row('z', c.z)}${row('Peak day', fmtDayY(e.chart.peak.d) + ', Florida ' + Math.round(e.chart.peak.t * 100) + '% vs donors ' + Math.round(e.chart.peak.o * 100) + '%')}
      </dl><p>${P.links && (P.links.csv_local || P.links.csv) ? `<a href="${esc(P.links.csv_local ? ROOT + P.links.csv_local : RM.STORAGE + P.links.csv)}" download>Download the daily series (CSV)</a>. ` : ''}Values are each region’s demand divided by its own mean over ${fmtDay(e.chart.pre_window[0])}–${fmtDay(e.chart.pre_window[1])}.</p></details>
      <details class="drawer"><summary>Baseline, lag and pre-trends</summary><dl class="dl">${row('Baseline', 'season-matched: the same dates in every other panel year, never after the event')}${row('Lag', `${e.lag_days} days to the peak gap; the pre-registered window has no lag`)}
      ${row('Leads (3 blocks before onset)', c.leads.join(', '))}${row('Pre-trend p', c.p_pre + ' (flat: p ≥ 0.10)')}</dl></details>
      <details class="drawer"><summary>Placebos, synthetic control, multiple testing</summary><dl class="dl">${row('In-space p (30 fake Floridas)', `${c.p_space} (1 in ${c.p_space_odds})`)}${row('In-time p (' + c.in_time.n + ' pseudo-storms)', c.p_time)}
      ${row('Synthetic control', `${c.synth_d} log pts, same sign; RMSPE ratio ${c.synth_ratio}, rank p ${c.synth_p}`)}${e.replication && e.replication.family ? row('Family q (24 hurricanes, BH)', e.replication.family.q + ' — ' + e.replication.family.strength) : ''}
      ${P.calibration && P.calibration.decoy_fp_rate != null ? row(`Decoy false-alarm rate${P.calibration.decoy_n ? ` (${P.calibration.decoy_n} sets)` : ''}`, `${Math.round(P.calibration.decoy_fp_rate * 1000) / 10}%${P.calibration.wilson ? ` [${P.calibration.wilson.map(x => Math.round(x * 1000) / 10).join(', ')}]` : ''}`) : ''}</dl></details>` : ''}
      ${e.forecast ? `<details class="drawer"><summary>The forecast check (BigQuery, ${esc(e.forecast.model)})</summary><dl class="dl">${e.forecast.series.map(s => row(`Series ${s.series_id}`, `${s.effect_pct}% [${s.lo_pct}, ${s.hi_pct}], p ${s.p}`)).join('')}${row('Verdict', `${e.forecast.state}: ${e.forecast.n_agree} of ${e.forecast.n_eligible} series`)}${e.forecast.calibration.map(c => row(`Calibration, ${c.role.replace('_', ' ')}`, `${c.hops_sig} of ${c.hops_evaluated} significant, ${c.hops_agree} agree`)).join('')}${row('Run', esc(e.forecast.run))}</dl></details>` : ''}
      <details class="drawer"><summary>Ledger and provenance</summary><dl class="dl">${row('Hop id', e.hop_id)}${L.register_seq ? row('Registered', `seq ${L.register_seq}${led && led[0] ? ', ' + fmtDayY(led[0].day) : ''}`) : ''}${led && led[0] && led[0].payload_hash ? row('Register hash', led[0].payload_hash, 1) : ''}
      ${L.freeze_seq ? row('Grid frozen', `seq ${L.freeze_seq}${P.engine && P.engine.batch ? ', batch ' + esc(P.engine.batch) : ''}`) : ''}${L.frozen_hash ? row('Frozen hash', L.frozen_hash, 1) : ''}${L.model_seq ? row('Model versions', L.model_seq.join(', ') + ' (6.2, 6.2.1)') : ''}${L.calibration_seq ? row('Calibration', 'seq ' + L.calibration_seq) : ''}${L.control_seq ? row('Control audit', `seq ${L.control_seq}`) : ''}${L.resolve_seq ? row('Resolved', `seq ${L.resolve_seq}${g.resolved_at ? ', ' + fmtDayY(g.resolved_at.slice(0, 10)) : ''}`) : ''}${L.publish_seq || L.version_seq ? row('Version published', `seq ${L.publish_seq || L.version_seq}`) : ''}${L.cascade_head ? row('Cascade ledger head', L.cascade_head, 1) : ''}
      ${P.ledger_head ? row('Chain head', `seq ${P.ledger_head.seq}`) + row('Head hash', P.ledger_head.chain_hash, 1) : ''}${c && c.computed_at ? row('Computed', c.computed_at.slice(0, 16).replace('T', ' ') + ' UTC') : ''}</dl><p><a href="${ROOT}how/">How Ripple Map knows</a>.</p></details>`;
  }
  global.RMEvidence = { init, luckPanel, forecastPanel, drawers };
})(window);
