-- Knock-On v5 / W2: seed data (generated from category-map.json; safe to re-run)
-- 1. category_map seed (source 'seed'); parents are filled by ripples-resolve when a class is first seen
insert into ripples.category_map (class_qid, category, label, flag, flag_reason, source) values
  ('Q1006311', 'other', 'war of national liberation', 'block', 'manual seed', 'seed'),
  ('Q100906234', 'other', 'multinational military coalition', null, null, 'seed'),
  ('Q101352', 'other', 'family name', null, null, 'seed'),
  ('Q1020018', 'other', 'stock market crash', null, null, 'seed'),
  ('Q102336293', 'other', 'live streaming service', null, null, 'seed'),
  ('Q102440913', 'other', 'digital public good', null, null, 'seed'),
  ('Q10269077', 'other', 'sertanejo duo', null, null, 'seed'),
  ('Q102786', 'other', 'abbreviation', null, null, 'seed'),
  ('Q103495', 'other', 'world war', 'block', 'manual seed', 'seed'),
  ('Q104212151', 'other', 'series of wars', 'block', 'manual seed', 'seed'),
  ('Q104782082', 'place', 'territory outside RCM in Quebec', null, null, 'seed'),
  ('Q1050260', 'sport', 'national sport', null, null, 'seed'),
  ('Q1051067', 'other', 'pre-dreadnought battleship', null, null, 'seed'),
  ('Q1058914', 'tech', 'software company', null, null, 'seed'),
  ('Q105985', 'politics_law', 'judiciary', null, null, 'seed'),
  ('Q1061197', 'film_tv', 'radio network', null, null, 'seed'),
  ('Q106389302', 'place', 'city/town in Russia', null, null, 'seed'),
  ('Q106652786', 'history_culture', 'entertainment newspaper', null, null, 'seed'),
  ('Q10689397', 'film_tv', 'television production company', null, null, 'seed'),
  ('Q10711424', 'place', 'state with limited recognition', null, null, 'seed'),
  ('Q107655869', 'other', 'group of awards', null, null, 'seed'),
  ('Q1080794', 'place', 'public school', null, null, 'seed'),
  ('Q108564724', 'politics_law', 'social democratic party', null, null, 'seed'),
  ('Q109288825', 'music', 'male duo', null, null, 'seed'),
  ('Q10931495', 'other', 'shizoku rebellion', 'block', 'manual seed', 'seed'),
  ('Q1093829', 'place', 'city in the United States', null, null, 'seed'),
  ('Q109473326', 'place', 'country in World War II', 'block', 'manual seed', 'seed'),
  ('Q11028', 'other', 'information', null, null, 'seed'),
  ('Q110315658', 'politics_law', 'elected legislative house', null, null, 'seed'),
  ('Q11042', 'history_culture', 'culture', null, null, 'seed'),
  ('Q110656899', 'film_tv', 'pornographic film distributor', 'block', 'manual seed', 'seed'),
  ('Q11074464', 'tech', 'pornography website', 'block', 'manual seed', 'seed'),
  ('Q110903080', 'other', 'unexplained disappearance of a human', 'block', 'manual seed', 'seed'),
  ('Q11204', 'politics_law', 'legislature', null, null, 'seed'),
  ('Q112057532', 'tech', 'type of technology', null, null, 'seed'),
  ('Q112099', 'place', 'island country', null, null, 'seed'),
  ('Q112193867', 'science_health', 'type of disease', null, null, 'seed'),
  ('Q1123840', 'other', 'symbols of Europe', null, null, 'seed'),
  ('Q1126006', 'film_tv', 'public broadcaster', null, null, 'seed'),
  ('Q1127126', 'politics_law', 'military alliance', null, null, 'seed'),
  ('Q112965645', 'science_health', 'symptom or sign', null, null, 'seed'),
  ('Q113145171', 'science_health', 'type of chemical entity', null, null, 'seed'),
  ('Q1135557', 'other', 'quartet', null, null, 'seed'),
  ('Q1139665', 'politics_law', 'political murder', 'block', 'manual seed', 'seed'),
  ('Q11396960', 'business', 'production company', null, null, 'seed'),
  ('Q114106', 'tech', 'metasearch engine', null, null, 'seed'),
  ('Q11422542', 'other', 'international conflict', 'block', 'manual seed', 'seed'),
  ('Q11424', 'film_tv', 'film', null, null, 'seed'),
  ('Q114955954', 'other', 'crowdsourced project', null, null, 'seed'),
  ('Q114962596', 'history_culture', 'historical position', null, null, 'seed'),
  ('Q11514315', 'history_culture', 'historical period', null, null, 'seed'),
  ('Q115305900', 'tech', 'large language model', null, null, 'seed'),
  ('Q115471117', 'other', 'self-depicting entity', null, null, 'seed'),
  ('Q11578153', 'music', 'male idol group', null, null, 'seed'),
  ('Q115915866', 'film_tv', 'award ceremony edition', null, null, 'seed'),
  ('Q11659239', 'history_culture', 'yūhan', null, null, 'seed'),
  ('Q1166072', 'business', 'financial transaction', null, null, 'seed'),
  ('Q116621859', 'place', 'Greater district town in Baden-Württemberg', null, null, 'seed'),
  ('Q116777014', 'tech', 'generative pre-trained transformer', null, null, 'seed'),
  ('Q117246174', 'tech', 'generative artificial intelligence', null, null, 'seed'),
  ('Q117349473', 'tech', 'artificial intelligence model', null, null, 'seed'),
  ('Q1179466', 'politics_law', 'de facto regime', null, null, 'seed'),
  ('Q118140435', 'tech', 'very large online platform', null, null, 'seed'),
  ('Q118322', 'other', 'involuntary manslaughter', 'block', 'manual seed', 'seed'),
  ('Q11862829', 'other', 'academic discipline', null, null, 'seed'),
  ('Q1187811', 'place', 'college town', null, null, 'seed'),
  ('Q1188693', 'sport', 'mind sport', null, null, 'seed'),
  ('Q1194040', 'history_culture', 'Hindu text', null, null, 'seed'),
  ('Q1195354', 'history_culture', 'public holiday in Japan', null, null, 'seed'),
  ('Q1197685', 'history_culture', 'public holiday', null, null, 'seed'),
  ('Q12100493', 'place', 'state fund', null, null, 'seed'),
  ('Q1221156', 'place', 'federated state of Germany', null, null, 'seed'),
  ('Q122754124', 'other', 'ambiguous Wikidata item', null, null, 'seed'),
  ('Q122759350', 'tech', 'user-generated content platform', null, null, 'seed'),
  ('Q123370638', 'tech', 'branch of computer science', null, null, 'seed'),
  ('Q12340140', 'history_culture', 'weekly magazine', null, null, 'seed'),
  ('Q123432', 'place', 'aristocracy', null, null, 'seed'),
  ('Q123458523', 'politics_law', 'violation of international law', null, null, 'seed'),
  ('Q123480', 'place', 'landlocked country', null, null, 'seed'),
  ('Q12443800', 'place', 'state of India', null, null, 'seed'),
  ('Q1244442', 'place', 'school building', null, null, 'seed'),
  ('Q124612203', 'other', 'massacre of civilians', 'block', 'manual seed', 'seed'),
  ('Q124757', 'other', 'riot', 'block', 'manual seed', 'seed'),
  ('Q1248784', 'place', 'airport', null, null, 'seed'),
  ('Q1250464', 'place', 'realm', null, null, 'seed'),
  ('Q125161275', 'other', 'type of intelligence', null, null, 'seed'),
  ('Q1254874', 'film_tv', 'television network', null, null, 'seed'),
  ('Q1255828', 'other', 'controversy', null, null, 'seed'),
  ('Q1259759', 'film_tv', 'miniseries', null, null, 'seed'),
  ('Q1261499', 'other', 'naval battle', 'block', 'manual seed', 'seed'),
  ('Q1262712', 'other', 'gas pipeline', null, null, 'seed'),
  ('Q1272194', 'other', 'tile-based game', null, null, 'seed'),
  ('Q1273203', 'other', 'mailbox provider', null, null, 'seed'),
  ('Q12759805', 'place', 'sultanate', null, null, 'seed'),
  ('Q13002315', 'history_culture', 'legendary figure', null, null, 'seed'),
  ('Q131569', 'politics_law', 'treaty', null, null, 'seed'),
  ('Q1322494', 'place', 'sociotope', null, null, 'seed'),
  ('Q13406463', 'other', 'Wikimedia list article', null, null, 'seed'),
  ('Q135054036', 'sport', 'men’s national volleyball team', null, null, 'seed'),
  ('Q13605686', 'history_culture', 'nude magazine', 'block', 'manual seed', 'seed'),
  ('Q13642845', 'politics_law', 'law enforcement jargon', null, null, 'seed'),
  ('Q1371849', 'film_tv', 'filmography', null, null, 'seed'),
  ('Q1391399', 'business', 'labor shortage', null, null, 'seed'),
  ('Q1407225', 'film_tv', 'television award', null, null, 'seed'),
  ('Q140892892', 'place', 'country sometimes considered transcontinental', null, null, 'seed'),
  ('Q1414729', 'film_tv', 'cinema film format', null, null, 'seed'),
  ('Q14350', 'film_tv', 'radio station', null, null, 'seed'),
  ('Q14660', 'history_culture', 'flag', null, null, 'seed'),
  ('Q14795564', 'other', 'point in time with respect to recurrent timeframe', null, null, 'seed'),
  ('Q149086', 'other', 'homicide', 'block', 'manual seed', 'seed'),
  ('Q15056993', 'tech', 'aircraft family', null, null, 'seed'),
  ('Q1509831', 'history_culture', 'titles of Mary, mother of Jesus', null, null, 'seed'),
  ('Q1520223', 'place', 'constitutional republic', null, null, 'seed'),
  ('Q15220419', 'other', 'word game', null, null, 'seed'),
  ('Q15265344', 'film_tv', 'broadcaster', null, null, 'seed'),
  ('Q1549591', 'place', 'big city', null, null, 'seed'),
  ('Q15632617', 'person', 'fictional human', null, null, 'seed'),
  ('Q1569167', 'film_tv', 'video game character', null, null, 'seed'),
  ('Q15773347', 'film_tv', 'film character', null, null, 'seed'),
  ('Q16510064', 'sport', 'sporting event', null, null, 'seed'),
  ('Q16521', 'science_health', 'taxon', null, null, 'seed'),
  ('Q167170', 'sport', 'multi-sport event', null, null, 'seed'),
  ('Q17127659', 'politics_law', 'terrorist organization', 'block', 'manual seed', 'seed'),
  ('Q17343829', 'place', 'unincorporated community', null, null, 'seed'),
  ('Q17374546', 'sport', 'Australian rules football club', null, null, 'seed'),
  ('Q178561', 'other', 'battle', 'block', 'manual seed', 'seed'),
  ('Q17888', 'other', 'sexual orientation', null, null, 'seed'),
  ('Q179164', 'place', 'unitary state', null, null, 'seed'),
  ('Q18011172', 'film_tv', 'film project', null, null, 'seed'),
  ('Q18608583', 'sport', 'recurring sporting event', null, null, 'seed'),
  ('Q18703581', 'other', 'game on cell board', null, null, 'seed'),
  ('Q18706315', 'other', 'hypothetical entity', null, null, 'seed'),
  ('Q1875621', 'tech', 'aircraft class', null, null, 'seed'),
  ('Q1941779', 'business', 'fashion house', null, null, 'seed'),
  ('Q198', 'other', 'war', 'block', 'manual seed', 'seed'),
  ('Q19967801', 'tech', 'online service', null, null, 'seed'),
  ('Q200250', 'place', 'metropolis', null, null, 'seed'),
  ('Q20053795', 'politics_law', 'Brazilian presidential election', null, null, 'seed'),
  ('Q20181813', 'place', 'colonial power', null, null, 'seed'),
  ('Q202686', 'place', 'Commonwealth realm', null, null, 'seed'),
  ('Q202866', 'film_tv', 'animated film', null, null, 'seed'),
  ('Q20643324', 'music', 'opera genre', null, null, 'seed'),
  ('Q207320', 'politics_law', 'paramilitary organization', 'block', 'manual seed', 'seed'),
  ('Q2119819', 'other', 'code of conduct', null, null, 'seed'),
  ('Q215380', 'music', 'musical group', null, null, 'seed'),
  ('Q216337', 'music', 'boy band', null, null, 'seed'),
  ('Q2223653', 'other', 'terrorist attack', 'block', 'manual seed', 'seed'),
  ('Q223832', 'history_culture', 'dominion of the British Empire', null, null, 'seed'),
  ('Q2245405', 'history_culture', 'key event', null, null, 'seed'),
  ('Q22988604', 'history_culture', 'mythological Greek character', null, null, 'seed'),
  ('Q23442', 'place', 'island', null, null, 'seed'),
  ('Q24451526', 'tech', 'data serialization format', null, null, 'seed'),
  ('Q24856', 'film_tv', 'film series', null, null, 'seed'),
  ('Q253030', 'place', 'major regional center', null, null, 'seed'),
  ('Q2661442', 'tech', 'W3C Recommendation', null, null, 'seed'),
  ('Q27020041', 'sport', 'sports season', null, null, 'seed'),
  ('Q28171280', 'history_culture', 'ancient civilization', null, null, 'seed'),
  ('Q2819161', 'sport', 'AFL Grand Final', null, null, 'seed'),
  ('Q28640', 'other', 'profession', null, null, 'seed'),
  ('Q28872924', 'place', 'designation for an administrative territorial entity of a single country', null, null, 'seed'),
  ('Q29380', 'tech', 'sponsored top-level domain', null, null, 'seed'),
  ('Q294414', 'politics_law', 'public office', null, null, 'seed'),
  ('Q30089777', 'politics_law', 'patriotic society', null, null, 'seed'),
  ('Q3024240', 'place', 'historical country', null, null, 'seed'),
  ('Q30941437', 'film_tv', 'pornographic film studio', 'block', 'manual seed', 'seed'),
  ('Q31629', 'sport', 'type of sport', null, null, 'seed'),
  ('Q3184121', 'place', 'municipality of Brazil', null, null, 'seed'),
  ('Q33283984', 'politics_law', 'Act of the Parliament of India', null, null, 'seed'),
  ('Q334453', 'other', 'division', null, null, 'seed'),
  ('Q3464665', 'film_tv', 'television series season', null, null, 'seed'),
  ('Q34918903', 'nature_weather', 'National Park of the United States', null, null, 'seed'),
  ('Q35127', 'tech', 'website', null, null, 'seed'),
  ('Q3624078', 'place', 'sovereign state', null, null, 'seed'),
  ('Q36646373', 'other', 'publication identifier', null, null, 'seed'),
  ('Q375011', 'history_culture', 'religious holiday', null, null, 'seed'),
  ('Q37726', 'politics_law', 'army', null, null, 'seed'),
  ('Q38033430', 'other', 'class of award', null, null, 'seed'),
  ('Q40231', 'politics_law', 'public election', null, null, 'seed'),
  ('Q40357', 'politics_law', 'prison', null, null, 'seed'),
  ('Q4128600', 'politics_law', 'State Duma election in Russia', null, null, 'seed'),
  ('Q41614', 'place', 'constitutional monarchy', null, null, 'seed'),
  ('Q4164871', 'politics_law', 'position', null, null, 'seed'),
  ('Q4167410', 'other', 'Wikimedia disambiguation page', null, null, 'seed'),
  ('Q4204501', 'history_culture', 'historical ethnic group', null, null, 'seed'),
  ('Q42045197', 'politics_law', 'hereditary position', null, null, 'seed'),
  ('Q4220917', 'film_tv', 'film award', null, null, 'seed'),
  ('Q43229', 'other', 'organization', null, null, 'seed'),
  ('Q43702', 'politics_law', 'federation', null, null, 'seed'),
  ('Q46135307', 'sport', 'nation at sport competition', null, null, 'seed'),
  ('Q467011', 'other', 'invasion', 'block', 'manual seed', 'seed'),
  ('Q476028', 'sport', 'association football club', null, null, 'seed'),
  ('Q482994', 'music', 'album', null, null, 'seed'),
  ('Q4830453', 'business', 'business', null, null, 'seed'),
  ('Q4989906', 'place', 'monument', null, null, 'seed'),
  ('Q5', 'person', 'human', null, null, 'seed'),
  ('Q51031626', 'sport', 'sport competition at a multi-sport event', null, null, 'seed'),
  ('Q515', 'place', 'city', null, null, 'seed'),
  ('Q51576574', 'place', 'Mediterranean country', null, null, 'seed'),
  ('Q51929311', 'place', 'largest city', null, null, 'seed'),
  ('Q5398426', 'film_tv', 'television series', null, null, 'seed'),
  ('Q559856', 'tech', 'online video platform', null, null, 'seed'),
  ('Q57780448', 'tech', 'semantic annotation format', null, null, 'seed'),
  ('Q59152282', 'tech', 'video streaming service', null, null, 'seed'),
  ('Q619610', 'place', 'social state', null, null, 'seed'),
  ('Q62049', 'place', 'county seat', null, null, 'seed'),
  ('Q6256', 'place', 'country', null, null, 'seed'),
  ('Q6266', 'place', 'nation', null, null, 'seed'),
  ('Q645883', 'other', 'military operation', 'block', 'manual seed', 'seed'),
  ('Q6576792', 'tech', 'online community', null, null, 'seed'),
  ('Q66715753', 'other', 'Wikimedia list of persons by position held', null, null, 'seed'),
  ('Q681263', 'tech', 'open standard', null, null, 'seed'),
  ('Q6881511', 'business', 'enterprise', null, null, 'seed'),
  ('Q7210356', 'politics_law', 'political organization', null, null, 'seed'),
  ('Q7270', 'place', 'republic', null, null, 'seed'),
  ('Q7278', 'politics_law', 'political party', null, null, 'seed'),
  ('Q750215', 'other', 'mass murder', 'block', 'manual seed', 'seed'),
  ('Q7725634', 'history_culture', 'literary work', null, null, 'seed'),
  ('Q7889', 'film_tv', 'video game', null, null, 'seed'),
  ('Q841985', 'history_culture', 'han', null, null, 'seed'),
  ('Q842402', 'history_culture', 'Hindu temple', null, null, 'seed'),
  ('Q8432', 'history_culture', 'civilization', null, null, 'seed'),
  ('Q8465', 'other', 'civil war', 'block', 'manual seed', 'seed'),
  ('Q857833', 'politics_law', 'state crime', 'block', 'manual seed', 'seed'),
  ('Q859563', 'place', 'secular state', null, null, 'seed'),
  ('Q891723', 'business', 'public company', null, null, 'seed'),
  ('Q90404711', 'film_tv', 'pornographic actor or erotic model database', 'block', 'manual seed', 'seed'),
  ('Q94993988', 'place', 'commercial traffic aerodrome', null, null, 'seed'),
  ('Q96382832', 'place', 'destroyed mosque', null, null, 'seed'),
  ('Q96741677', 'sport', 'mountaineering expedition', null, null, 'seed'),
  ('Q979507', 'history_culture', 'Hindu deity', null, null, 'seed'),
  ('Q99527517', 'other', 'collective entity', null, null, 'seed')
on conflict (class_qid) do update set category = excluded.category, flag = excluded.flag,
  flag_reason = coalesce(excluded.flag_reason, ripples.category_map.flag_reason), source = 'seed', updated_at = now();

-- 2. blocklist class QIDs (labels verified against Wikidata)
insert into ripples.blocklist (qid, reason, action) values
  ('Q4', 'class: death', 'block'),
  ('Q7283', 'class: terrorism', 'block'),
  ('Q10737', 'class: suicide', 'block'),
  ('Q41397', 'class: genocide', 'block'),
  ('Q83267', 'class: crime', 'block'),
  ('Q124490', 'class: violence', 'block'),
  ('Q185529', 'class: pornographic film', 'block'),
  ('Q459409', 'class: hate crime', 'block'),
  ('Q744913', 'class: aviation accident', 'block'),
  ('Q1139665', 'class: political murder', 'block'),
  ('Q198', 'class: war', 'block'),
  ('Q178561', 'class: battle', 'block'),
  ('Q645883', 'class: military operation', 'block'),
  ('Q2223653', 'class: terrorist attack', 'block'),
  ('Q149086', 'class: homicide', 'block'),
  ('Q750215', 'class: mass murder', 'block'),
  ('Q8465', 'class: civil war', 'block'),
  ('Q467011', 'class: invasion', 'block'),
  ('Q3882219', 'class: assassination', 'block'),
  ('Q124757', 'class: riot', 'block'),
  ('Q173462', 'class: crime against humanity', 'block'),
  ('Q17127659', 'class: terrorist organization', 'block'),
  ('Q21480300', 'class: mass shooting', 'block'),
  ('Q110903080', 'class: unexplained disappearance of a human', 'block'),
  ('Q1331380', 'class: derailment', 'block'),
  ('Q13634374', 'class: ethnic violence', 'block'),
  ('Q30941437', 'class: pornographic film studio', 'block'),
  ('Q8065', 'class: natural disaster', 'sensitive'),
  ('Q7944', 'class: earthquake', 'sensitive'),
  ('Q8068', 'class: flood', 'sensitive'),
  ('Q8070', 'class: tsunami', 'sensitive'),
  ('Q8081', 'class: tornado', 'sensitive'),
  ('Q8092', 'class: tropical cyclone', 'sensitive'),
  ('Q81054', 'class: storm', 'sensitive'),
  ('Q167903', 'class: landslide', 'sensitive'),
  ('Q169950', 'class: wildfire', 'sensitive'),
  ('Q215864', 'class: heat wave', 'sensitive'),
  ('Q7692360', 'class: volcanic eruption', 'sensitive'),
  ('Q168983', 'class: conflagration', 'sensitive'),
  ('Q12184', 'class: pandemic', 'sensitive'),
  ('Q44512', 'class: epidemic', 'sensitive')
on conflict do nothing;

-- 3. re-derive auto classes and article flags
select ripples._rederive_classes(null);
select ripples._refresh_articles(array(select qid from ripples.articles));
