"""Build demo/discovered_wiki.json: the engine-found, hand-screened Wikipedia pairs, with each mark's date verified
against its article's lead (year and month must appear) under the honest UA, one request a second."""
import json, re, sys
from legacy import get, clean
S = json.load(open("stones_all.json"))
W = lambda t: "https://en.wikipedia.org/wiki/" + t.replace(" ", "_")
def M(label, title, kind, date, prec, sentence, src_article, src_section, found, mark_article):
    return {"label": label, "title": title, "kind": kind, "date": date, "precision": prec, "sentence": sentence, "source_label": f"Wikipedia: {src_article}" + (f", {src_section}" if src_section else ""), "source_url": W(src_article) + (("#" + src_section.replace(" ", "_")) if src_section else ""), "found": found, "mark_url": W(mark_article) if mark_article else None, "mark_article": mark_article}
stones = {
 "sixty-minutes-stock-act": {"stone": "60 Minutes", "article": "60 Minutes", "date": S["sixty-minutes-stock-act"]["date"], "title": "60 Minutes → the STOCK Act", "first": "60 Minutes airs its segment on congressional insider trading", "marks": [
   M("STOCK Act", "The STOCK Act is signed into law", "Law", "2012-04-04", "day", "Originally written and introduced by Washington congressman Brian Baird, the STOCK Act gained popularity following a 60 Minutes segment on congressional insider trading in 2011, after which Republican senator Scott Brown and Democratic senator Kirsten Gillibrand introduced bills.", "STOCK Act", "", "reverse", "STOCK Act")]},
 "west-wing-hatred-act": {"stone": "The West Wing", "article": "The West Wing", "date": S["west-wing-hatred-act"]["date"], "title": "The West Wing → the Racial and Religious Hatred Act 2006", "first": "The West Wing airs \"A Good Day\"", "marks": [
   M("Racial and Religious Hatred Act 2006", "The Racial and Religious Hatred Act 2006 receives royal assent, as amended after the government's defeat", "Law", "2006-02-16", "day", "The Tories' strategy to win the vote was inspired by \"A Good Day\", an episode of American television series The West Wing.", "Racial and Religious Hatred Act 2006", "", "reverse", "Racial and Religious Hatred Act 2006")]},
 "silent-spring-ddt": {"stone": "Silent Spring", "article": "Silent Spring", "date": S["silent-spring-ddt"]["date"], "title": "Silent Spring → the National Environmental Policy Act", "first": "Silent Spring is published", "marks": [
   M("NEPA", "The National Environmental Policy Act is signed", "Law", "1970-01-01", "day", "During this time, environmental interest group efforts and the growing public awareness resulting from Rachel Carson's 1962 book Silent Spring led to support for the 1964 Wilderness Act and subsequent legislation (including the 1969 National Environmental Policy Act).", "National Environmental Policy Act", "", "reverse", "National Environmental Policy Act")]},
 "sputnik-nasa-arpa": {"stone": "Sputnik", "article": "Sputnik 1", "date": S["sputnik-nasa-arpa"]["date"], "title": "Sputnik → the National Defense Education Act", "first": "Sputnik 1 reaches orbit", "marks": [
   M("National Defense Education Act", "The National Defense Education Act is signed", "Law", "1958-09-02", "day", "The early Soviet success in the Space Race catalyzed a national sense of unease with Soviet technological advances, especially after the Soviet Union launched the first-ever satellite, Sputnik, the previous year.", "National Defense Education Act", "", "reverse", "National Defense Education Act")]},
 "love-canal-superfund": {"stone": "Love Canal", "article": "Love Canal", "date": S["love-canal-superfund"]["date"], "title": "Love Canal → the ATSDR", "first": "Love Canal is declared a federal emergency", "marks": [
   M("ATSDR", "CERCLA creates the Agency for Toxic Substances and Disease Registry", "Institution", "1980-12-11", "day", "In response to the environmental disasters at Love Canal and Times Beach, Missouri, Congress passed the Comprehensive Environmental Response, Compensation, and Liability Act of 1980 (CERCLA), commonly known as the Superfund Act, which created the ATSDR.", "Agency for Toxic Substances and Disease Registry", "", "reverse", "Agency for Toxic Substances and Disease Registry")]},
 "exxon-valdez-opa90": {"stone": "The Exxon Valdez", "article": "Exxon Valdez oil spill", "date": S["exxon-valdez-opa90"]["date"], "title": "Exxon Valdez → the Oil Pollution Act and a state commission", "first": "The Exxon Valdez runs aground on Bligh Reef", "marks": [
   M("Alaska Oil Spill Commission", "Alaska's legislature creates the Alaska Oil Spill Commission", "Institution", "1989", "year", "The Exxon Valdez Oil Spill Commission (the Alaska Oil Spill Commission) was created by the Alaska Legislature in 1989 to review the spill and recommend changes.", "Exxon Valdez oil spill", "", "reverse", "Exxon Valdez oil spill"),
   M("Oil Pollution Act of 1990", "The Oil Pollution Act of 1990 is signed", "Law", "1990-08-18", "day", "Laws governing oil spills in the United States began in 1851 with the Limitation of Liability Act; the Oil Pollution Act of 1990 was passed following the Exxon Valdez spill.", "Oil Pollution Act of 1990", "", "reverse", "Oil Pollution Act of 1990")]},
 "columbine-active-shooter": {"stone": "Columbine", "article": "Columbine High School massacre", "date": S["columbine-active-shooter"]["date"], "title": "Columbine → New Jersey's anti-bullying law", "first": "The Columbine High School massacre", "marks": [
   M("New Jersey anti-bullying law", "New Jersey enacts its first anti-bullying law, later strengthened as the Anti-Bullying Bill of Rights Act (2011)", "Law", "2002", "year", "A majority of states created these laws in response to a number of high school shootings that occurred throughout the 1990s, the most widely known being the Columbine High School massacre.", "New Jersey Anti-Bullying Bill of Rights Act", "", "reverse", "New Jersey Anti-Bullying Bill of Rights Act")]},
 "flint-lead-pipes": {"stone": "Flint", "article": "Flint water crisis", "date": S["flint-lead-pipes"]["date"], "title": "Flint → the Lead and Copper Rule revisions", "first": "Flint switches its water source to the Flint River", "marks": [
   M("Lead and Copper Rule revisions", "The EPA publishes revisions to the Lead and Copper Rule", "Regulation", "2021-01-15", "day", "In response to the Flint, Michigan water crisis, EPA published revisions to the Lead and Copper Rule on January 15, 2021 addressing testing, pipe replacement and related issues.", "Safe Drinking Water Act", "", "reverse", "Lead and Copper Rule")]},
 "fukushima": {"stone": "Fukushima", "article": "Fukushima nuclear accident", "date": S["fukushima"]["date"], "title": "Fukushima → four new institutions in Japan and Korea", "first": "The Fukushima Daiichi nuclear accident begins", "marks": [
   M("Korea's NSSC", "South Korea establishes the Nuclear Safety and Security Commission", "Institution", "2011-10-26", "day", "The NSSC was established on October 26, 2011, to bolster nuclear safety amid widespread public fears after the Fukushima Daiichi disaster in March and several incidents at Korean reactors.", "Nuclear Safety and Security Commission", "", "reverse", "Nuclear Safety and Security Commission"),
   M("NAIIC", "The Diet's Fukushima Nuclear Accident Independent Investigation Commission is formed", "Institution", "2011-12-08", "day", "National Diet of Japan Fukushima Nuclear Accident Independent Investigation Commission or NAIIC is the commission to investigate the background and cause of Fukushima Daiichi nuclear disaster formed by the statutory law enactment by the Diet.", "National Diet of Japan Fukushima Nuclear Accident Independent Investigation Commission", "", "reverse", "National Diet of Japan Fukushima Nuclear Accident Independent Investigation Commission"),
   M("Reconstruction Agency", "Japan establishes the Reconstruction Agency", "Institution", "2012-02-10", "day", "The Reconstruction Agency is an agency of the Japanese government established on February 10, 2012, to coordinate reconstruction activities related to the 2011 Tōhoku earthquake and tsunami and Fukushima Daiichi nuclear disaster.", "Reconstruction Agency", "", "reverse", "Reconstruction Agency"),
   M("Nuclear Regulation Authority", "Japan's Nuclear Regulation Authority replaces NISA", "Institution", "2012-09-19", "day", "After the Fukushima nuclear disaster following the March 11, 2011, earthquake, the government's safety measures were seen to be inadequate.", "Nuclear Regulation Authority", "", "reverse", "Nuclear Regulation Authority")]},
 "anthrax": {"stone": "The anthrax letters", "article": "2001 anthrax attacks", "date": S["anthrax"]["date"], "title": "The anthrax letters → the Patriot Act", "first": "The first anthrax letters are mailed", "marks": [
   M("Patriot Act", "The Patriot Act is signed", "Law", "2001-10-26", "day", "The Patriot Act was enacted following the September 11 attacks and the 2001 anthrax attacks with the stated goal of tightening U.S. national security, particularly as it related to foreign terrorism.", "Patriot Act", "", "reverse", "Patriot Act")]},
 "an-inconvenient-truth": {"stone": "An Inconvenient Truth", "article": "An Inconvenient Truth", "date": "2006-05-24", "title": "An Inconvenient Truth → a climate institution and a court ruling", "first": "An Inconvenient Truth opens", "marks": [
   M("The Climate Reality Project", "Gore founds the Alliance for Climate Protection, now The Climate Reality Project", "Institution", "2006", "year", "Following the film, Gore founded The Climate Reality Project in 2006 which trained 1,000 activists to give Gore's presentation in their communities.", "An Inconvenient Truth", "Activism", "forward", "The Climate Reality Project"),
   M("The Dimmock ruling", "The High Court rules on showing the film in English schools", "Legal", "2007-10-10", "day", "On October 10, 2007, High Court Justice Michael Burton ruled that the film could be shown in schools with guidance notes addressing nine points of departure from the mainstream scientific position.", "An Inconvenient Truth", "Dimmock case", "forward", "Dimmock v Secretary of State for Education and Skills")]},
 "the-day-after": {"stone": "The Day After", "article": "The Day After", "date": "1983-11-20", "title": "The Day After → the INF Treaty", "first": "ABC broadcasts The Day After", "marks": [
   M("INF Treaty", "Reagan and Gorbachev sign the Intermediate-Range Nuclear Forces Treaty", "Treaty", "1987-12-08", "day", "He wrote in his diary that the film was \"very effective and left me greatly depressed\" and that it changed his mind on the prevailing policy on a \"nuclear war\". In 1987, Reagan and Soviet Premier Mikhail Gorbachev signed the Intermediate-Range Nuclear Forces Treaty.", "The Day After", "Effects on policymakers", "forward", "Intermediate-Range Nuclear Forces Treaty")]},
 "deepwater-horizon": {"stone": "Deepwater Horizon", "article": "Deepwater Horizon oil spill", "date": "2010-04-20", "title": "Deepwater Horizon → a commission, a council, a health study, a new bureau", "first": "The Deepwater Horizon rig explodes", "marks": [
   M("National Commission", "The National Commission on the BP Deepwater Horizon Oil Spill is established by executive order", "Institution", "2010-05-21", "day", "The National Commission on the BP Deepwater Horizon Oil Spill and Offshore Drilling is a bipartisan presidential commission, established by Executive Order 13543 signed by Barack Obama on May 21, 2010.", "National Commission on the BP Deepwater Horizon Oil Spill and Offshore Drilling", "", "reverse", "National Commission on the BP Deepwater Horizon Oil Spill and Offshore Drilling"),
   M("GuLF Study", "Health and Human Services sets up the GuLF Study of cleanup workers", "Public health", "2010-06", "month", "The United States Department of Health and Human Services set up the GuLF Study in June 2010 in response to these reports.", "Deepwater Horizon oil spill", "Health consequences", "forward", "GuLF Study"),
   M("National Ocean Council", "An executive order citing the spill establishes the National Ocean Council", "Institution", "2010-07-19", "day", "In July 2010, President Obama issued an executive order, specifically citing the Deepwater Horizon oil spill, that adopted recommendations from the Interagency Ocean Policy Task Force and established the National Ocean Council.", "Deepwater Horizon oil spill", "U.S. reactions", "forward", None),
   M("BSEE", "The Bureau of Safety and Environmental Enforcement opens, splitting the old Minerals Management Service", "Institution", "2011-10-01", "day", "The Bureau of Safety and Environmental Enforcement was created on October 1, 2011 as part of the reorganization of the Minerals Management Service after the Deepwater Horizon oil spill.", "Bureau of Safety and Environmental Enforcement", "", "reverse", "Bureau of Safety and Environmental Enforcement"),
   M("BP contracting ban", "The EPA suspends BP from new federal contracts", "Policy", "2012-11-28", "day", "The U.S. government temporarily banned BP from new federal contracts over its \"lack of business integrity\".", "Deepwater Horizon oil spill", "Civil litigation and prosecution", "forward", None)]},
 "sandy-hook": {"stone": "Sandy Hook", "article": "Sandy Hook Elementary School shooting", "date": "2012-12-14", "title": "Sandy Hook → two state gun laws and a records carve-out", "first": "The Sandy Hook Elementary School shooting", "marks": [
   M("NY SAFE Act", "New York enacts the SAFE Act", "Law", "2013-01-15", "day", "On January 16, 2013, New York became the first U.S. state to act after the shooting when it enacted the Secure Ammunition and Firearms Enforcement (SAFE) Act.", "Sandy Hook Elementary School shooting", "Gun control", "forward", "NY SAFE Act"),
   M("Connecticut's gun law", "Connecticut passes a 139-page gun law with the first dangerous-weapon offender registry", "Law", "2013-04-04", "day", "On April 3, 2013, the Connecticut General Assembly passed a 139-page major gun-control bill with broad bipartisan support. It also created the first registry in the United States for dangerous-weapon offenders, and added over 100 types of guns to the state's assault weapons ban.", "Sandy Hook Elementary School shooting", "Gun control", "forward", "Gun laws in Connecticut"),
   M("Connecticut FOIA change", "Connecticut amends its Freedom of Information Act to withhold crime-scene images", "Law", "2013-06-05", "day", "On June 5, both houses of the Connecticut state legislature passed a bill modifying the state's Freedom of Information Act in order to prevent the release of crime-scene photos and video evidence.", "Sandy Hook Elementary School shooting", "Aftermath", "forward", None)]},
}
# verify: the mark article's lead (or the source article) carries the year and, for day or month precision, the month
MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"]
bad = 0
for slug, st in stones.items():
    for i, m in enumerate(st["marks"]):
        m["id"] = f"w{i}"
        art = m["mark_article"] or (m["source_label"].split(": ", 1)[1].split(", ")[0])
        d = get({"action": "parse", "page": art, "prop": "wikitext", "redirects": 1}); txt, _ = clean(d.get("parse", {}).get("wikitext", {}).get("*", ""))
        y = m["date"][:4]; ok_y = y in txt; ok_m = True
        if m["precision"] != "year": mon = MONTHS[int(m["date"][5:7]) - 1]; ok_m = (mon in txt) or (mon[:3] + " " in txt)
        flag = "" if (ok_y and ok_m) else "  <-- CHECK"; bad += not (ok_y and ok_m)
        print(f"{slug[:22]:22s} {m['label'][:30]:30s} {m['date']:10s} {m['precision']:5s} | year in article {ok_y} month {ok_m}{flag}")
out = {"_about": "Engine-found pairs from Wikipedia read as a cited-cause record (docs/discovery_corpus1_v1.md): the stone's article and the articles of laws and institutions that link to it, read for a sentence that names a lasting change with a causal word; each mark dated from the record; the ordering rule applied; every pair shown was confirmed by a person on Oct 4, 2026. A sentence is a reported link, never measured.", "run": "2026-10-04", "stones": stones}
json.dump(out, open("../site/ripples/demo/discovered_wiki.json", "w"), indent=1, ensure_ascii=False)
print("\nstones", len(stones), "marks", sum(len(s["marks"]) for s in stones.values()), "flagged", bad)
