// node ripples/tools/build.mjs   (Ripple Map v6, WS-D)
// Bundles and minifies the readable sources (ripples/app.js, ui.js, line.js, lists.js, lib.js, config.js and app.css) into ripples/dist/, which is
// what every /ripples/ page loads: EXPERIENCE §11 caps HTML + CSS + JS at 120 KB per page, uncompressed. No framework and no
// runtime dependency; esbuild is a build-time tool only (npx fetches it). Each output starts with a hash of the sources, and
// tools/test-lib.mjs fails when dist/ is stale, so edit the sources and re-run this script.
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
export const SOURCES = ['app.js', 'ui.js', 'line.js', 'evidence.js', 'lists.js', 'help.js', 'lib.js', 'config.js', 'app.css'];
export const SHELLS = ['index.html', 'line/index.html', 'map/index.html', 'lands/index.html', 'week/index.html', 'archive/index.html', 'methods/index.html'];
export const srcHash = () => createHash('sha256').update(SOURCES.map(f => readFileSync(join(root, f), 'utf8')).join('\n/*--*/\n')).digest('hex').slice(0, 16);

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = join(root, 'dist'); mkdirSync(out, { recursive: true });
  const h = srcHash();
  const esb = process.env.ESBUILD || 'npx';
  const pre = esb === 'npx' ? ['--yes', 'esbuild@0.25.10'] : [];
  const run = args => execFileSync(esb, [...pre, ...args], { cwd: root, stdio: ['ignore', 'pipe', 'inherit'] });
  for (const f of readdirSync(out)) if (/\.(js|css)$/.test(f)) rmSync(join(out, f));
  // app.js is the entry; line.js and lists.js are loaded with import() and become their own chunks (a page loads only its own)
  run(['app.js', '--bundle', '--splitting', '--format=esm', '--minify', '--target=es2020,safari14', '--legal-comments=none', '--chunk-names=[name]', '--entry-names=[name]', `--banner:js=/*! Knock-On Ripple Map ${h}: built from ripples/*.js by tools/build.mjs */`, '--outdir=dist']);
  run(['app.css', '--minify', '--target=safari14', `--banner:css=/*! Knock-On Ripple Map ${h}: built from ripples/app.css */`, '--outfile=dist/app.css']);
  for (const f of readdirSync(out)) console.log(`dist/${f}: ${statSync(join(out, f)).size} bytes`);
  // Inline the minified CSS into every shell: a render-blocking stylesheet request cost ~0.6–0.9 s of LCP on slow 4G.
  // gen-stubs.mjs copies the shells' <head>, so every stub carries it too. The <style id="rm-css"> block is replaced in place.
  // @font-face rules are left out of the inline copy: ui.js registers the fonts with the FontFace API once the page has
  // painted, so 100 KB of fonts never compete with the first render (Lighthouse mobile LCP 1.8 s → 1.2 s in testing).
  // The /ripples/pro/ compatibility block (rules scoped to body:not([data-route]) and its :root token aliases) is dropped
  // from the inline copy too: every shell and stub carries data-route, and /pro/ loads ripples/app.css itself.
  const proOnly = sel => sel.split(',').every(x => x.trim().startsWith('body:not([data-route])')) || /^:root$/.test(sel.trim());
  const css = readFileSync(join(out, 'app.css'), 'utf8').replace(/@font-face\{[^}]*url\([^}]*\}/g, '')
    .replace(/(?<=^|[{}])([^{}@]+)\{([^{}]*)\}/g, (m, sel, body) => (proOnly(sel) && (!/^:root$/.test(sel.trim()) || /^--line:/.test(body)) ? '' : m))
    .replace(/<\/style/gi, '<\\/style').trim();
  for (const shell of SHELLS) {
    const p = join(root, shell); let t = readFileSync(p, 'utf8');
    const tag = `<style id="rm-css">${css}</style>`;
    t = /<style id="rm-css">[\s\S]*?<\/style>/.test(t) ? t.replace(/<style id="rm-css">[\s\S]*?<\/style>/, () => tag) : t.replace('<link rel="stylesheet" href="/ripples/dist/app.css">', () => tag);
    writeFileSync(p, t);
  }
  console.log(`inlined ${css.length} bytes of CSS into ${SHELLS.length} shells`);
  writeFileSync(join(out, 'README.md'), `Generated by \`node ripples/tools/build.mjs\` from ripples/app.js, lib.js, config.js and app.css (source hash ${h}). Do not edit.\n`);
}
