// node ripples/tools/build.mjs   (Ripple Map v6, WS-D)
// Bundles and minifies the readable sources (ripples/app.js, ui.js, line.js, lists.js, lib.js, config.js and app.css) into ripples/dist/, which is
// what every /ripples/ page loads: EXPERIENCE §11 caps HTML + CSS + JS at 120 KB per page, uncompressed. No framework and no
// runtime dependency; esbuild is a build-time tool only (npx fetches it). Each output starts with a hash of the sources, and
// tools/test-lib.mjs fails when dist/ is stale, so edit the sources and re-run this script.
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
export const SOURCES = ['app.js', 'ui.js', 'line.js', 'lists.js', 'lib.js', 'config.js', 'app.css'];
export const srcHash = () => createHash('sha256').update(SOURCES.map(f => readFileSync(join(root, f), 'utf8')).join('\n/*--*/\n')).digest('hex').slice(0, 16);

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = join(root, 'dist'); mkdirSync(out, { recursive: true });
  const h = srcHash();
  const esb = process.env.ESBUILD || 'npx';
  const pre = esb === 'npx' ? ['--yes', 'esbuild@0.25.10'] : [];
  const run = args => execFileSync(esb, [...pre, ...args], { cwd: root, stdio: ['ignore', 'pipe', 'inherit'] });
  for (const f of readdirSync(out)) if (/\.(js|css)$/.test(f)) rmSync(join(out, f));
  // app.js is the entry; line.js and lists.js are loaded with import() and become their own chunks (a page loads only its own)
  run(['app.js', '--bundle', '--splitting', '--format=esm', '--minify', '--target=es2020,safari14', '--legal-comments=none', '--chunk-names=[name]', '--entry-names=[name]', `--banner:js=/*! Knock-On Ripple Map ${h}: built from ripples/*.js by tools/build.mjs */`, '--outdir=dist']);
  run(['app.css', '--minify', '--target=safari14', `--banner:css=/*! Knock-On Ripple Map ${h}: built from ripples/app.css */`, '--outfile=dist/app.css']);
  for (const f of readdirSync(out)) console.log(`dist/${f}: ${statSync(join(out, f)).size} bytes`);
  writeFileSync(join(out, 'README.md'), `Generated by \`node ripples/tools/build.mjs\` from ripples/app.js, lib.js, config.js and app.css (source hash ${h}). Do not edit.\n`);
}
