// node ripples/tools/gen-stubs.mjs [max=400]
// Writes ripples/{n}/index.html and ripples/{n}/{s}/index.html (s = 0..4) from ripples/index.html.
// Each stub is the same shell with data-n / data-s, noindex,follow, canonical /ripples/{n}/ and a
// per-puzzle og:image from the ripples-og edge function, so shared links unfurl before any JS runs.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const MAX = +(process.argv[2] || 400);
const OG = 'https://kffkasnzqcddpystszch.supabase.co/functions/v1/ripples-og';
const tpl = readFileSync(root + 'index.html', 'utf8');

function sub(html, re, to) {
  const m = html.match(new RegExp(re.source, 'g'));
  if (!m || m.length !== 1) throw new Error(`template: expected exactly one match for ${re}, got ${m ? m.length : 0}`);
  return html.replace(re, to);
}
function stub(n, s) {
  const page = s == null ? `https://bensunter.com/ripples/${n}/` : `https://bensunter.com/ripples/${n}/${s}/`;
  const img = s == null ? `${OG}?n=${n}` : `${OG}?n=${n}&amp;s=${s}`;
  const title = `Knock-On #${n}`;
  const ogTitle = s == null ? `Knock-On #${n} · a daily attention puzzle` : `Knock-On #${n}: found ${s} first try. Can you beat it?`;
  let h = tpl;
  h = sub(h, /<title>[^<]*<\/title>/, `<title>${title}</title>`);
  h = sub(h, /(<meta name="viewport"[^>]*>)/, `$1\n<meta name="robots" content="noindex,follow">\n<!-- generated by ripples/tools/gen-stubs.mjs from ripples/index.html; edit the template, not this file -->`);
  h = sub(h, /<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="https://bensunter.com/ripples/${n}/">`);
  h = sub(h, /<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${ogTitle}">`);
  h = sub(h, /<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${page}">`);
  h = sub(h, /<meta property="og:image" content="[^"]*">/, `<meta property="og:image" content="${img}">`);
  h = sub(h, /<meta name="twitter:image" content="[^"]*">/, `<meta name="twitter:image" content="${img}">`);
  h = sub(h, /<body>/, `<body data-n="${n}"${s == null ? '' : ` data-s="${s}"`}>`);
  return h;
}
let count = 0;
for (let n = 1; n <= MAX; n++) {
  mkdirSync(`${root}${n}`, { recursive: true });
  writeFileSync(`${root}${n}/index.html`, stub(n, null)); count++;
  for (let s = 0; s <= 4; s++) {
    mkdirSync(`${root}${n}/${s}`, { recursive: true });
    writeFileSync(`${root}${n}/${s}/index.html`, stub(n, s)); count++;
  }
}
console.log(`wrote ${count} stubs for n=1..${MAX}`);
